"""scholarship sources

Revision ID: 9dac93660dc5
Revises: bfabef01e539
Create Date: 2026-08-17 22:39:16.473650
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '9dac93660dc5'
down_revision = 'bfabef01e539'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholarship_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scholarship_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scholarship_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scholarship_sources_scholarship_id'), ['scholarship_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scholarship_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scholarship_sources_scholarship_id'))

    op.drop_table('scholarship_sources')
    # ### end Alembic commands ###
