"""initial schema

Revision ID: bfabef01e539
Revises: 
Create Date: 2026-08-17 22:16:49.189867
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = 'bfabef01e539'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cover_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('fact_check_report', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cover_letters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cover_letters_user_id'), ['user_id'], unique=False)

    op.create_table('cv_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('target_role', sa.String(length=255), nullable=True),
    sa.Column('version_label', sa.String(length=80), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('json_snapshot', sa.Text(), nullable=True),
    sa.Column('fact_check_report', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cv_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cv_versions_user_id'), ['user_id'], unique=False)

    op.create_table('deadlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.String(length=30), nullable=False),
    sa.Column('reminder_days', sa.Integer(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deadlines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deadlines_entity_id'), ['entity_id'], unique=False)

    op.create_table('llm_usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('task', sa.String(length=120), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('in_app', sa.Boolean(), nullable=False),
    sa.Column('email', sa.Boolean(), nullable=False),
    sa.Column('telegram', sa.Boolean(), nullable=False),
    sa.Column('whatsapp', sa.Boolean(), nullable=False),
    sa.Column('high_match_job', sa.Boolean(), nullable=False),
    sa.Column('high_eligibility_scholarship', sa.Boolean(), nullable=False),
    sa.Column('deadline_approaching', sa.Boolean(), nullable=False),
    sa.Column('application_ready', sa.Boolean(), nullable=False),
    sa.Column('interview_scheduled', sa.Boolean(), nullable=False),
    sa.Column('followup_due', sa.Boolean(), nullable=False),
    sa.Column('expired', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=True)

    op.create_table('result_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('result_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_result_cache_content_hash'), ['content_hash'], unique=False)

    op.create_table('scholarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('university', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('programme', sa.String(length=255), nullable=True),
    sa.Column('degree_level', sa.String(length=60), nullable=True),
    sa.Column('funding_level', sa.String(length=60), nullable=True),
    sa.Column('tuition_coverage', sa.Text(), nullable=True),
    sa.Column('accommodation', sa.Text(), nullable=True),
    sa.Column('living_allowance', sa.Text(), nullable=True),
    sa.Column('travel_allowance', sa.Text(), nullable=True),
    sa.Column('insurance', sa.Text(), nullable=True),
    sa.Column('application_fee', sa.Text(), nullable=True),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('required_classification', sa.Text(), nullable=True),
    sa.Column('required_field', sa.Text(), nullable=True),
    sa.Column('work_experience_required', sa.Text(), nullable=True),
    sa.Column('english_requirement', sa.Text(), nullable=True),
    sa.Column('age_requirement', sa.Text(), nullable=True),
    sa.Column('deadline', sa.String(length=30), nullable=True),
    sa.Column('application_url', sa.Text(), nullable=True),
    sa.Column('official_url', sa.Text(), nullable=True),
    sa.Column('open_to_kenyans', sa.Boolean(), nullable=False),
    sa.Column('open_to_africans', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('eligibility_label', sa.String(length=30), nullable=True),
    sa.Column('discovery_date', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('duplicate_group', sa.String(length=64), nullable=True),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scholarships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scholarships_duplicate_group'), ['duplicate_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_scholarships_name'), ['name'], unique=False)

    op.create_table('search_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('finished_at', sa.String(), nullable=True),
    sa.Column('results_found', sa.Integer(), nullable=False),
    sa.Column('new_opportunities', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cadence', sa.String(length=30), nullable=True),
    sa.Column('last_run_at', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('verification_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('check_name', sa.String(length=120), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=40), nullable=True),
    sa.Column('checked_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_results_entity_id'), ['entity_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('doc_type', sa.String(length=60), nullable=False),
    sa.Column('extraction_status', sa.String(length=20), nullable=False),
    sa.Column('uploaded_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_user_id'), ['user_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('organization_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.String(length=80), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('preferred_requirements', sa.JSON(), nullable=True),
    sa.Column('deadline', sa.String(length=30), nullable=True),
    sa.Column('application_url', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=False),
    sa.Column('is_international', sa.Boolean(), nullable=False),
    sa.Column('curriculum', sa.String(length=100), nullable=True),
    sa.Column('discovery_date', sa.String(), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('duplicate_group', sa.String(length=64), nullable=True),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('eligibility', sa.String(length=30), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('is_ai_training', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_duplicate_group'), ['duplicate_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_title'), ['title'], unique=False)

    op.create_table('master_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('phone_encrypted', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('profession', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('professional_registration', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('master_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('scholarship_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('cv_version_id', sa.Integer(), nullable=True),
    sa.Column('cover_letter_id', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.String(length=30), nullable=True),
    sa.Column('salary', sa.String(length=120), nullable=True),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('date_discovered', sa.String(), nullable=True),
    sa.Column('date_applied', sa.String(), nullable=True),
    sa.Column('interview_date', sa.String(length=30), nullable=True),
    sa.Column('follow_up_date', sa.String(length=30), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cover_letter_id'], ['cover_letters.id'], ),
    sa.ForeignKeyConstraint(['cv_version_id'], ['cv_versions.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_user_id'), ['user_id'], unique=False)

    op.create_table('certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('issuer', sa.String(length=200), nullable=True),
    sa.Column('date_earned', sa.String(length=20), nullable=True),
    sa.Column('reference_number', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['master_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certifications_profile_id'), ['profile_id'], unique=False)

    op.create_table('document_extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=120), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_extractions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_extractions_document_id'), ['document_id'], unique=False)

    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=200), nullable=True),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('field', sa.String(length=200), nullable=True),
    sa.Column('classification', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['master_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_education_profile_id'), ['profile_id'], unique=False)

    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('subjects', sa.JSON(), nullable=True),
    sa.Column('grades', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['master_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experience_profile_id'), ['profile_id'], unique=False)

    op.create_table('job_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_sources_job_id'), ['job_id'], unique=False)

    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('level', sa.String(length=40), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['master_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_profile_id'), ['profile_id'], unique=False)

    op.create_table('application_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=120), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_answers_application_id'), ['application_id'], unique=False)

    op.create_table('application_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_events_application_id'), ['application_id'], unique=False)

    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('interview_date', sa.String(length=30), nullable=True),
    sa.Column('format', sa.String(length=80), nullable=True),
    sa.Column('panel', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interviews_application_id'), ['application_id'], unique=False)

    op.create_table('interview_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('model_answer', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_questions_interview_id'), ['interview_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_questions_interview_id'))

    op.drop_table('interview_questions')
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interviews_application_id'))

    op.drop_table('interviews')
    with op.batch_alter_table('application_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_events_application_id'))

    op.drop_table('application_events')
    with op.batch_alter_table('application_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_answers_application_id'))

    op.drop_table('application_answers')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_profile_id'))

    op.drop_table('skills')
    with op.batch_alter_table('job_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_sources_job_id'))

    op.drop_table('job_sources')
    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experience_profile_id'))

    op.drop_table('experience')
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_education_profile_id'))

    op.drop_table('education')
    with op.batch_alter_table('document_extractions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_extractions_document_id'))

    op.drop_table('document_extractions')
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certifications_profile_id'))

    op.drop_table('certifications')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_user_id'))

    op.drop_table('applications')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('master_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_profiles_user_id'))

    op.drop_table('master_profiles')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_title'))
        batch_op.drop_index(batch_op.f('ix_jobs_duplicate_group'))

    op.drop_table('jobs')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_user_id'))

    op.drop_table('documents')
    with op.batch_alter_table('verification_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_results_entity_id'))

    op.drop_table('verification_results')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('search_sources')
    op.drop_table('search_runs')
    with op.batch_alter_table('scholarships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scholarships_name'))
        batch_op.drop_index(batch_op.f('ix_scholarships_duplicate_group'))

    op.drop_table('scholarships')
    with op.batch_alter_table('result_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_result_cache_content_hash'))

    op.drop_table('result_cache')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_name'))

    op.drop_table('organizations')
    op.drop_table('notification_preferences')
    op.drop_table('llm_usage_log')
    with op.batch_alter_table('deadlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deadlines_entity_id'))

    op.drop_table('deadlines')
    with op.batch_alter_table('cv_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cv_versions_user_id'))

    op.drop_table('cv_versions')
    with op.batch_alter_table('cover_letters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cover_letters_user_id'))

    op.drop_table('cover_letters')
    # ### end Alembic commands ###
