"""matching fields and notification entity

Revision ID: d4ea14dd3211
Revises: 9dac93660dc5
Create Date: 2026-08-18 12:53:48.665197
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = 'd4ea14dd3211'
down_revision = '9dac93660dc5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_details', sa.JSON(), nullable=True))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_type', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('entity_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('scholarships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('match_details', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scholarships', schema=None) as batch_op:
        batch_op.drop_column('match_details')
        batch_op.drop_column('priority_score')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('entity_id')
        batch_op.drop_column('entity_type')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('match_details')

    # ### end Alembic commands ###
